---
- name: Ensure jenkins directory on docker host
  file:
    path: /share/jenkins
    owner: devops
    group: devops
    state: directory

- name: Pull official Jenkins image and create Jenkins container
  docker_container:
    name: jenkins-server
    state: started
    image: jenkins/jenkins:lts
    pull: true
    volumes:
      - "/share/jenkins:/var/jenkins_home"
    ports:
      - "8001:8080"
      - "50000:50000"