---
- name: Ensure jenkins directory on docker host
  file:
    path: /share/jenkins
    owner: devops
    group: devops
    state: directory
    mode: 0777

- name: Update APT packages
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Pull official Jenkins image and create Jenkins container
  become: true
  become_user: root
  become_method: sudo
  docker_container:
    name: jenkins-server
    state: started
    image: jenkins/jenkins:lts
    pull: true
    detach: yes
    volumes:
      - "/share/jenkins:/var/jenkins_home:rw"
    ports:
      - "8080:8080"
      - "50000:50000"