---
- name: Ensure jenkins directory on docker host
  file:
    path: /share/jenkins
    owner: devops
    group: devops
    state: directory

- name: Login to Docker Hub Registry
  docker_login:
    email: "srik1980@gmail.com"
    username: "srik1980"
    password: "Berlin123@"

- name: Pull official Jenkins image and create Jenkins container
  become: true
  docker_container:
    name: jenkins-server
    state: started
    image: jenkins/jenkins:latest
    pull: true
    volumes:
      - "/share/jenkins:/var/jenkins_home"
    ports:
      - "8001:8080"
      - "50000:50000"