---
- name: Ensure jenkins directory on docker host
  file:
    path: /share/jenkins
    owner: devops
    group: devops
    state: directory

# - name: Login to Docker Hub Registry
#   docker_login:
#     email: "srik1980@gmail.com"
#     username: "srik1980"
#     password: "Berlin123@"

- name: Update APT packages
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Pull official Jenkins image and create Jenkins container
  become: true
  docker_container:
    name: jenkins-server
    state: started
    image: jenkins/jenkins:latest
    pull: true
    detach: yes
    volumes:
      - "/share/jenkins:/var/jenkins_home"
    # exposed_ports:
    #     - "8080"
    ports:
      - "8080:8080"
      - "50000:50000"

# - name: Pull latest official Jenkins Docker image
#   docker_image: 
#     name: jenkins/jenkins:lts
#     source: pull

# - name: Create Jenkins docker container from pulled Jenkins image
#   docker_container:
#     name: jenkins-server
#     image: jenkins
#     ports:
#       - "8001:8080"
#       - "50000:50000"
#     volumes:
#       - "/share/jenkins:/var/jenkins_home"
#     state: present
#     recreate: no