---
- name: Ensure jenkins directory on docker host
  file:
    path: /share/jenkins
    owner: devops
    group: devops
    state: directory

- name: Pull latest official Jenkins Docker image
  docker_image: 
    name: jenkins/jenkins:lts
    source: pull

- name: Create Jenkins docker container from pulled Jenkins image
  docker_container:
    name: jenkins-server
    image: jenkins
    ports:
      - "8001:8080"
      - "50000:50000"
    volumes:
      - "/share/jenkins:/var/jenkins_home"
    state: present
    recreate: no

