- hosts: tools
  strategy: debug
  user: vagrant
  become: yes
  become_method: sudo
  become_user: root
  roles: 
   - docker-debian
  # - openJDK
   - oracleJDK
   - docker-jenkins
   - docker-nginx
  
  